spring:
  application:
    name: transit
  datasource:
    url: jdbc:postgresql://localhost:5433/transit
    username: transit
    password: transit
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
